# This file was generated by GoReleaser. DO NOT EDIT.
cask "autoreview" do
  version "0.7.3"

  on_macos do
    on_intel do
      sha256 "ba6a82416b1936dc304d683b680bd90506e7f72e16fa0c2d450fbfcc692ba9a7"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
    on_arm do
      sha256 "2f66b6cb35eaa386a3dda96a469e122b7f5e0dc1e8eda8bf8cb3def64c537c32"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2833d9fa9ef40254f92e4fb9343681836cdcb610ac2edba7483b1d534ca5f2c8"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
    on_arm do
      sha256 "632aa23e9f4cbb9c153c110e285c667e438a0eb7f35ccae192b9d0f850e762b0"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
  end

  name "autoreview"
  desc "Structured independent code review CLI"
  homepage "https://github.com/uinaf/autoreview"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "trufflehog",
    ]

  binary "autoreview"

  # No zap stanza required

end
