# This file was generated by GoReleaser. DO NOT EDIT.
cask "autoreview" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "330ec84f682fdd441cb8d62e68f508d2233bacff95dd01102781f9d99944df53"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
    on_arm do
      sha256 "6eb63b5746ed331c65d0a03e9b48f8d1707c6959c70ca6849eda83ea8a1e64d6"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2bf446afeca080e89cfa03169178f4e9846b7b640fdc92e8ae3fa8c573e69950"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
    on_arm do
      sha256 "700566f93f358c45de18ab73bbcf7c6076e45982cdf1f28e349ee4bd9b9285ac"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
  end

  name "autoreview"
  desc "Structured independent code review CLI"
  homepage "https://github.com/uinaf/autoreview"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "trufflehog",
    ]

  binary "autoreview"

  # No zap stanza required

end
