# This file was generated by GoReleaser. DO NOT EDIT.
cask "autoreview" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "5456ecf49b75b083b381e6ddd455b1b791058b2d9470e432706497acccb6936a"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
    on_arm do
      sha256 "8b6c028adddb25f15b577433cafc21ff16a68de6359fbc2dd4d2a76c4ed9f531"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
  end

  on_linux do
    on_intel do
      sha256 "13c0f522a2852cf1b49ebdda078e5c8036bfac181a855647eaf73557d246dd9a"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
    on_arm do
      sha256 "1d3973cf9395dbf9a6353f49fdc34087ac2e0f97d69b1f9ab703df67f6f8e4b1"
      url "https://github.com/uinaf/autoreview/releases/download/v#{version}/autoreview_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/autoreview/"
    end
  end

  name "autoreview"
  desc "Structured independent code review CLI"
  homepage "https://github.com/uinaf/autoreview"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "trufflehog",
    ]

  binary "autoreview"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/autoreview"]
    end
  end

  # No zap stanza required

end
