# This file was generated by the ffss release workflow. DO NOT EDIT.
cask "slopguard" do
  version "2.0.2"

  on_macos do
    on_intel do
      sha256 "608e131e3c84819b0d2f3f94a71c22649c11676a859b749551f87512eeb658d2"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d3eb98b2d5d0e88c0ef269313ebe01c01b391c2892c9a367084ed24432c4f0f"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a524c96aaecc38e1e9160436ee2fa0c6fb4c00587a5b88f07fc1c55028efbc2"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "18cd7fc8ded926bda126cb38c9ad3e9ec27b56de39549b30f32df89bdc86b37f"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_linux_arm64.tar.gz"
    end
  end

  livecheck do
    url :homepage
    regex(%r{slopguard/v?(\d+(?:\.\d+)+)}i)
    strategy :github_releases
  end

  depends_on formula: "git"
  name "slopguard"

  binary "slopguard"

  homepage "https://github.com/uinaf/ffss"
  desc "Structured independent code review as a CLI and agent skill"
end
