# This file was generated by the ffsstack release workflow. DO NOT EDIT.
cask "slopmachine" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "ab65627ebf335774fc1c651c111a3b990ee515a8e0e80aaf62b73f422bfe1331"
      url "https://github.com/uinaf/ffsstack/releases/download/slopmachine%2Fv1.1.0/slopmachine_v1.1.0_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
    on_arm do
      sha256 "749257b8dd63821b0ce4c3269b6a04b7d3d3e41dc2c8fb431318358527ac53b6"
      url "https://github.com/uinaf/ffsstack/releases/download/slopmachine%2Fv1.1.0/slopmachine_v1.1.0_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a7a34ae56bf31368810e208d4bf59e3a67a46b55deea197f06e80fe3252d0da8"
      url "https://github.com/uinaf/ffsstack/releases/download/slopmachine%2Fv1.1.0/slopmachine_v1.1.0_linux_amd64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
    on_arm do
      sha256 "7f1ce7f4702263bc3c8d302e8ea1696724579ba194882912436918f5a41b302a"
      url "https://github.com/uinaf/ffsstack/releases/download/slopmachine%2Fv1.1.0/slopmachine_v1.1.0_linux_arm64.tar.gz",
        verified: "github.com/uinaf/ffsstack/"
    end
  end

  binary "slopmachine"

  homepage "https://github.com/uinaf/ffsstack"
  desc "Deterministic and structured approach to slop cannoning"
end
