# This file was generated by the ffss release workflow. DO NOT EDIT.
cask "slopmachine" do
  version "1.10.2"

  on_macos do
    on_intel do
      sha256 "2c29a69669e57b3c6dce57226a5d3ff986ebb25191050d09312911e59aa9f5fc"
      url "https://github.com/uinaf/ffss/releases/download/slopmachine%2Fv#{version}/slopmachine_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
    on_arm do
      sha256 "78eb8be24d3cb3a7de9e585ee3b7072a7677f26f4d04b1ff1968cc8912662022"
      url "https://github.com/uinaf/ffss/releases/download/slopmachine%2Fv#{version}/slopmachine_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
  end

  on_linux do
    on_intel do
      sha256 "8fb6eb1b2a4ae26ad80f2a883acfb9565bc70034cac87da9ee19b23a9a391c93"
      url "https://github.com/uinaf/ffss/releases/download/slopmachine%2Fv#{version}/slopmachine_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
    on_arm do
      sha256 "ac017168a389aca67a4a386004008c9cb2acbc603715b556be8bbbcc7664e5a3"
      url "https://github.com/uinaf/ffss/releases/download/slopmachine%2Fv#{version}/slopmachine_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
  end

  livecheck do
    url :homepage
    regex(%r{slopmachine/v?(\d+(?:\.\d+)+)}i)
    strategy :github_releases
  end

  name "slopmachine"

  binary "slopmachine"

  homepage "https://github.com/uinaf/ffss"
  desc "Deterministic and structured approach to slop cannoning"
end
