# This file was generated by GoReleaser. DO NOT EDIT.
cask "slopomatic" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "92ecbf0b790f65210def00c798dd3257e55567e78bfd4d0f638bf5316a333283"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
    on_arm do
      sha256 "b7ad0f8c525f33560c95afccf5e6163556445b022bfe003146d4dc67b95f0905"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f4d54e33bfb68e3c6fb1875a91dbfbd359719b5ea431e86d0c83b764858c162"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
    on_arm do
      sha256 "02431be40880c4763c9b2f45bc10cbeb156b762f722031202a51306a032bb791"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
  end

  name "slopomatic"
  desc "Deterministic and structured approach to slop cannoning"
  homepage "https://github.com/uinaf/slopomatic"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slopomatic"

  # No zap stanza required

end
