# This file was generated by GoReleaser. DO NOT EDIT.
cask "slopomatic" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "a974bdfe81af069fd0da3bbfb1ac5d8505775e0b57afbbb10d2f9c4f055c0235"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
    on_arm do
      sha256 "93c095eb8f39a9fc142cad09853d8b5cbf588aa24c6927454ac0b8c01fd489fb"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
  end

  on_linux do
    on_intel do
      sha256 "75856f9e0e42cba4682377ac937b0307bb4b110499fa888a58408cb8cb006ecb"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
    on_arm do
      sha256 "1a6b3e805cef230b2c902564cb8717e44bad82a1d0cfcb09457d10c6a31fd213"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
  end

  name "slopomatic"
  desc "Deterministic and structured approach to slop cannoning"
  homepage "https://github.com/uinaf/slopomatic"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slopomatic"

  # No zap stanza required

end
