# This file was generated by GoReleaser. DO NOT EDIT.
cask "slopomatic" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "fd1fbd2a2bf4f19d0f5fd700462c41d63a084dad7992b59774bca0060621560f"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
    on_arm do
      sha256 "39c58d981a250374d0296f1e3761b10de30f5d2c2fe577e755097b7f0abb2a92"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5659559e2a42987a57d86f11cee69c046da8edd59be2e923a2d8fe35b6c733a5"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
    on_arm do
      sha256 "e5ee076c19e0fd8cdedf8ae3edadfe647a9885df229044005f094414890f5ec1"
      url "https://github.com/uinaf/slopomatic/releases/download/v#{version}/slopomatic_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/slopomatic/"
    end
  end

  name "slopomatic"
  desc "Deterministic and structured approach to slop cannoning"
  homepage "https://github.com/uinaf/slopomatic"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slopomatic"

  # No zap stanza required

end
