# This file was generated by the ffss release workflow. DO NOT EDIT.
cask "slopguard" do
  version "1.9.1"

  on_macos do
    on_intel do
      sha256 "2db96c96fa07d5d530e3ceed61eccfd0caa5da8119ce427b0b8ae91eb2157675"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
    on_arm do
      sha256 "a56813ce5517d66468547b255afa569c857bfce36af63391026c041c194a52c4"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
  end

  on_linux do
    on_intel do
      sha256 "62566baee0fb77536890e14f2c98c8db490e9d4216996b326d40b1d9fa9e1a15"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
    on_arm do
      sha256 "62f5dbb1899e5c64d28ddd90e6d80418c1b0bdf6228f9c9a17573764baaf4564"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/ffss/"
    end
  end

  livecheck do
    url :homepage
    regex(%r{slopguard/v?(\d+(?:\.\d+)+)}i)
    strategy :github_releases
  end

  depends_on formula: [
      "git",
      "trufflehog",
    ]
  name "slopguard"

  binary "slopguard"

  homepage "https://github.com/uinaf/ffss"
  desc "Structured independent code review as a CLI and agent skill"
end
