# This file was generated by the ffss release workflow. DO NOT EDIT.
cask "slopguard" do
  version "2.3.0"

  on_macos do
    on_intel do
      sha256 "b82c06ef9d6be3bc35d4848991b4136da887ed6650fcd575de4cb7909e823fbd"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b381686ca4fabf34df8e54fa611d1d2d0add119e19ca13d56bb177033d8e9826"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "748f429572388fdcaabd9bc65255d57be84e7cedabe7e34cf004969eef9454c0"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "06cddd4a816ce9d7a9124230500e11b58cc4a4ddaece0a85eba08f7b7d738eec"
      url "https://github.com/uinaf/ffss/releases/download/slopguard%2Fv#{version}/slopguard_v#{version}_linux_arm64.tar.gz"
    end
  end

  livecheck do
    url :homepage
    regex(%r{slopguard/v?(\d+(?:\.\d+)+)}i)
    strategy :github_releases
  end

  depends_on formula: "git"
  name "slopguard"

  binary "slopguard"

  homepage "https://github.com/uinaf/ffss"
  desc "Structured independent code review as a CLI and agent skill"
end
