# This file was generated by GoReleaser. DO NOT EDIT.
cask "slopshipper" do
  version "3.1.0"

  on_macos do
    on_intel do
      sha256 "7c9ae211c115db9eda39cd774eaeadf582b5d4b67fa555932b6c6742198cf300"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
    on_arm do
      sha256 "c3100317ec3dd3c83b3ddf4f797b56e68c7b35b195e9f3ee45a60dd8a7f8f68e"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
  end

  on_linux do
    on_intel do
      sha256 "d370b5a18dd00dffabc0e1df42ec3b9c7cd9ae9f7ba792ce8238c3463b71976b"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
    on_arm do
      sha256 "93f777c3b2e3d2233ff1e686e4869fe1ba517241f150c4eda40c0ae9c77373ff"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
  end

  name "slopshipper"
  desc "Deterministic and structured approach to slop cannoning"
  homepage "https://github.com/uinaf/slopshipper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slopshipper"

  # No zap stanza required

end
