# This file was generated by GoReleaser. DO NOT EDIT.
cask "slopshipper" do
  version "2.1.1"

  on_macos do
    on_intel do
      sha256 "8604e1c1dc6d27431422358b040a67d5c137b0bc101445745041c888071a89f7"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
    on_arm do
      sha256 "de260fee71a3e168b0777719f1988f835139ef80f709bfcacd2dd2a688dbd723"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
  end

  on_linux do
    on_intel do
      sha256 "dcbc83e7d401ed1d2ecf60f854dfcd2e90199dc1a300475452e25451c2da60b6"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
    on_arm do
      sha256 "9d9a9a8a3fafdbe1ba2559abade0d37f1d1642aa8b3d85ac51a6adf54ae3d22e"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
  end

  name "slopshipper"
  desc "Deterministic and structured approach to slop cannoning"
  homepage "https://github.com/uinaf/slopshipper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slopshipper"

  # No zap stanza required

end
