# This file was generated by GoReleaser. DO NOT EDIT.
cask "slopshipper" do
  version "2.1.2"

  on_macos do
    on_intel do
      sha256 "94b21d002bae83472da30f05c0c1f2bd002b62ce1e454d7ceb431991c6f74300"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
    on_arm do
      sha256 "3c2ff2e43b196d316c303a10957952f93fd5142245907639ca467e0803cee425"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef1d8d6a940f988bd07f2622a7b9ddc4060bd6ab552a9d1837a490971728070a"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
    on_arm do
      sha256 "dc71ac8d054f002e461abeb07a1b36beb46e45b5646566d46b885b17f278b8d8"
      url "https://github.com/uinaf/slopshipper/releases/download/v#{version}/slopshipper_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/uinaf/slopshipper/"
    end
  end

  name "slopshipper"
  desc "Deterministic and structured approach to slop cannoning"
  homepage "https://github.com/uinaf/slopshipper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slopshipper"

  # No zap stanza required

end
