# This file was generated by the ffss release workflow. DO NOT EDIT.
cask "slopmachine" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "22831c6655c24b035a410d90ed4b283576cc49f463bbddd6392bfa916f5f80ce"
      url "https://github.com/uinaf/ffss/releases/download/slopmachine%2Fv#{version}/slopmachine_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef5e9cddeef4d551e557040d0380fe3d05c8e552be476d1277452ef5adf10a2f"
      url "https://github.com/uinaf/ffss/releases/download/slopmachine%2Fv#{version}/slopmachine_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a716a89e082311b503a442dbc6172a6fa897d2f645a4b978dd60c819fa933c3c"
      url "https://github.com/uinaf/ffss/releases/download/slopmachine%2Fv#{version}/slopmachine_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0b0392d4a16c7e1249896620c07402d0c9d3d5d6626305cd97b7c2272fcd46d"
      url "https://github.com/uinaf/ffss/releases/download/slopmachine%2Fv#{version}/slopmachine_v#{version}_linux_arm64.tar.gz"
    end
  end

  livecheck do
    url :homepage
    regex(%r{slopmachine/v?(\d+(?:\.\d+)+)}i)
    strategy :github_releases
  end

  name "slopmachine"

  binary "slopmachine"

  homepage "https://github.com/uinaf/ffss"
  desc "Deterministic and structured approach to slop cannoning"
end
