# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Healthd < Formula
  desc "Pluggable local host health-check daemon"
  homepage "https://github.com/uinaf/healthd"
  version "0.5.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/uinaf/healthd/releases/download/v0.5.2/healthd_v0.5.2_darwin_amd64.tar.gz"
    sha256 "9fd4345334fc031380f9841fcf5d74e4cf28c177cad946458967c731653e5623"

    define_method(:install) do
      bin.install "healthd"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/uinaf/healthd/releases/download/v0.5.2/healthd_v0.5.2_darwin_arm64.tar.gz"
    sha256 "2312d44b0c8c0eac54cadb112804b3a43b8b0eb5bf1b728b28b7f7bfba16b36d"

    define_method(:install) do
      bin.install "healthd"
    end
  end

  test do
    assert_match "healthd", shell_output("#{bin}/healthd --help")
  end
end
