# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Healthd < Formula
  desc "Pluggable local host health-check daemon"
  homepage "https://github.com/uinaf/healthd"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/uinaf/healthd/releases/download/v0.5.1/healthd_v0.5.1_darwin_amd64.tar.gz"
    sha256 "0d77b2d0679cd68c91a64bf17fa405c00b296da9253a09e2043c0f4a6ac046e3"

    define_method(:install) do
      bin.install "healthd"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/uinaf/healthd/releases/download/v0.5.1/healthd_v0.5.1_darwin_arm64.tar.gz"
    sha256 "ea59c80511465fbafc14a88863df34e3ae3a1d941590672b625cdca89b65b0b6"

    define_method(:install) do
      bin.install "healthd"
    end
  end

  test do
    assert_match "healthd", shell_output("#{bin}/healthd --help")
  end
end
