# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class TccutilRs < Formula
  desc "Macos tcc.db management utility"
  homepage "https://github.com/uinaf/tccutil-rs"
  url "https://github.com/uinaf/tccutil-rs/archive/refs/tags/v0.2.12.tar.gz"
  sha256 "6c5ae13f5fa527245a750a4efacc0a54bcae401aa244b34b15acc720eca41fcd"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/uinaf/tccutil-rs/releases/download/v0.2.12/tccutil-rs-0.2.12-darwin-amd64.tar.gz"
      sha256 "efe036aa5dffd6ad934f370880db5c876f55a52b254c750f75889842cdb2712b"
    end

    on_arm do
      url "https://github.com/uinaf/tccutil-rs/releases/download/v0.2.12/tccutil-rs-0.2.12-darwin-arm64.tar.gz"
      sha256 "1a17d266feb5629f179011f4c8279df1e2921f33f728d4306b0e4b913c9b350c"
    end
  end

  def install
    bin.install "tccutil-rs"
  end

  test do
    assert_match "Manage macOS TCC permissions", shell_output("#{bin}/tccutil-rs --help")
  end
end
