# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class TccutilRs < Formula
  desc "Macos tcc.db management utility"
  homepage "https://github.com/uinaf/tccutil-rs"
  url "https://github.com/uinaf/tccutil-rs/archive/refs/tags/v0.2.11.tar.gz"
  sha256 "a50aaab5af873c7bee4d6e660fb7bc9bc4e2863bfc978a73eac667876731b0fc"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/uinaf/tccutil-rs/releases/download/v0.2.11/tccutil-rs-0.2.11-darwin-amd64.tar.gz"
      sha256 "aeca7e27f016cf934683a7fdcb1e153e144c96e7c23bda66a2158c367f53f019"
    end

    on_arm do
      url "https://github.com/uinaf/tccutil-rs/releases/download/v0.2.11/tccutil-rs-0.2.11-darwin-arm64.tar.gz"
      sha256 "4fced493a1298e248e7e1781c415abc8858d5a005e78ae47d0e78c8fc4d1d1d3"
    end
  end

  def install
    bin.install "tccutil-rs"
  end

  test do
    assert_match "Manage macOS TCC permissions", shell_output("#{bin}/tccutil-rs --help")
  end
end
